[package]
name = "ajobqueue"
version = "0.1.0"
edition = "2021"

[lib]
name = "ajobqueue"

[dependencies]
ajobqueue-macro = { path = "macro" }

async-trait = "0.1.56"
erased-serde = "0.3.21"
linkme = "0.3.1"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
tokio = { version = "1.20.0", features = ["rt", "macros", "sync"] }
typetag = "0.2.1"
